### ISSUE TITLE
Freezes at certain % of calculating transition probabilities

### ISSUE THREAD

**Issue by Pyatkova** [jagodki/Offline-MapMatching#23]
Hello, 

Thanks a lot for sharing your software!

I made several runs with different parameters and the plugin always freezes at 8 % of calculating the transition probabilities. When that happens, I cannot see whether there is an error message at all. Tried the following:

-using a metric CRS

-using only 14 points with 4 sec intervals

-using different maximum search distances (up to 350 m)

Any ideas what might be wrong?

**Comment by jagodki** [comment]
Hello,

first I have to excuse me for the late respond. I was very busy the last days. But now I found the time to answer you 😸 

To judge about your case is difficult, but your preparations sounds quite good. I have to confess that I had never freezed the plugin, so this would be the first time ^^

Could you provide a screenshot of your trajectory and the network? You could also upload your data (if possible) so that I could debug it on my machine. If you want to debug the data by yourself and if you are familiar with Python, than you could add the following code at line 135 in the file <a href="https://github.com/jagodki/Offline-MapMatching/blob/master/src/offlinemapmatching/mm/hidden_states/hidden_model.py">hidden_model.py</a> (directly after the start of a for loop) on your computer:
```python
print(i)
```
This will print the index of the positions of your trajectory while calculating the transition probabilities. A transition is builded up by candidates of the positions i and i-1 of your trajectory. You will get the information, at which trajectory point the plugin will stuck. Maybe there is a very special situation in your network so that the calculations will run very long. A maximum search distance with a value of 350m is quite big, maybe the plugin found some candidates (too) far away.

Let me know about your results, if you would debug it by your own.

Sincerely,
Christoph

**Comment by Pyatkova** [comment]
Hey Christoph, 

Thank you for your reply. I decided to use Barefoot to do the same thing. Tried your suggestion but could not make it work, but also did not spend as much time as I wish I could.

Best wishes, 

Katya
