### ISSUE TITLE
Toolbox dialog doesn't allow layer selection

### ISSUE THREAD

**Issue by lxrichert** [jagodki/Offline-MapMatching#28]
Hi, I am using QGIS 3.8.1 on Linux and can't slesct any layers in the toolbox plugin pop-up. I do have 2 layers with the LineString geometry and Point geometry, so I think it should be displaying something. Is it maybe due to the newer version of QGIS?

I can get it to run using the python console, but it breaks off quickly. The error code is -1 - what does this mean?

**Comment by jagodki** [comment]
Hi,

First try to use the main gui of the plugin (via the vector menu). Can you choose your layers there? The combo boxes in the main gui and the processing gui have different techniques behind them. Maybe this could be a problem. 

Error code -1 means, that the plugin cannot create the candidate graph. Maybe because the search distance is too low, maybe because a layer is missing. All error messages will be printed to the QGIS log (but I have to work on more detailed error messages...). 

Please let me know, if the problem also appears in the main gui. 

Sincerely,
Christoph

**Comment by DylanCheung** [comment]
Hi,

I get the same problem. The toolbox dialog doesn't allow layer selection even via the vector menu. I am working on QGIS 3.8 and 3.10 with Windows 10. 
Can you inform me which QGIS version is appliable with the plugin?

Best regards,
Kevin

**Comment by jagodki** [comment]
Hi Kevin,

for me it works with QGIS 3.4 and 3.10. If you start the plugin via the vector menu, only layers with single geometries (points and linestrings) should be available in the combo boxes. If you start the plugin via the toolbox, also layers with multigeometries should be selectable (but using such layers with the plugin is not recommended). 

Can you choose your layers with other algorithms from the toolbox? For the toolbox integration I am using the standard dialogue and layer selection. So it would be very weird, if this would not working. Do you have any error messages in the QGIS log?

Could you provide a screenshot of you QGIS project with the layers into it, that will not be selectable from the plugin? Maybe also a screenshot from the general settings of the layers (with information about source, crs, geometry type etc.)?

Sincerely,
Christoph

**Comment by DylanCheung** [comment]
Hi Christoph,

Thank you for your response.
I am using the network layer (testSegments.shp) and trajectory layer (testTrack.shp) from the material provided by https://github.com/simonscheider/mapmatching.

Please check out the attachment.

Best regards,
Kevin

[OfflineMapMatching.zip](https://github.com/jagodki/Offline-MapMatching/files/4562013/OfflineMapMatching.zip)

**Comment by jagodki** [comment]
I tried to reproduce your problem using the data you provided.

If I launch the plugin via the vector menu, I cannot choose the network layer, but the trajectory layer:
<img width="791" alt="main_before" src="https://user-images.githubusercontent.com/23242936/80913181-f79f6d80-8d42-11ea-820f-e152c6026a48.png">

But if I start the plugin via the toolbox, the network layer can be chosen:
<img width="800" alt="processing" src="https://user-images.githubusercontent.com/23242936/80913195-1271e200-8d43-11ea-8fc1-19a306d3e193.png">

The reason is very simple: the provided network layer has the geometry type MultiLineString (such layers are not available in the main GUI, but in the processing GUI). It is strictly recommended to use single geometries for this plugin. Multi geometries are not tested and can produce incorrect results. So please use the function "Multipart to singleparts" to create a network layer with the geometry type LineString. After this, the network is selectable via the main GUI (if you start the plugin via the vector menu):
<img width="791" alt="main_after" src="https://user-images.githubusercontent.com/23242936/80913240-72688880-8d43-11ea-9982-fd1bc9ff66f7.png">

With this network layer, the map matching works very well:
<img width="610" alt="result" src="https://user-images.githubusercontent.com/23242936/80913243-7eece100-8d43-11ea-942b-e0ca396f5d52.png">

**Comment by DylanCheung** [comment]
Thank you for your advice. It is very helpful. The map matching works very well right now. Thanks.

**Comment by jagodki** [comment]
closed because solved
