### ISSUE TITLE
I can't see the red line!

### ISSUE THREAD

**Issue by visile** [jagodki/Offline-MapMatching#37]
Hello, I'm the first time to use QGIS. When I match the map according to the test data you provided, I can get the matched trajectory layer, but I can't see it（red line） when I zoom to the layer. I don't know where to turn it on, and can I return to the code of the road？I can‘t understand the next ...
'''
Store the path in a new layer
The founded Viterbi path represents the vertices of the resulting line. A routing between following points of the Viterbi path returns linestrings, which will be written to a new memory layer. If you start the plugin with its GUI, i.e. not from the toolbox, the plugin provides a style file, so that the new layer will be displayed as a red line.
'''

**Comment by jagodki** [comment]
Hi,

did you start the plugin from the toolbox or from the vector menu? The result layer will only be displayed as red lines, if you start the plugin from the vector menu.

Does the plugin finished without problems? Does the result layer contain any features (open the attribute table of the resulting, if it is empty, then there is a problem)?

Could you tell me the parameters you used, so that I can try to reproduce the problem?

**Comment by visile** [comment]
Hello，
I enabled the plugin from the vector menu The attribute table in the layer contains content, but the zooming layer can't see the red line. I enabled the plugin again from the toolbox and saved the layer, but still can't see the matched track. Another problem is if I have many tracks that need map matching, can I use Python for automatic processing? How to adjust the parameters if the conditions of each track are different? 
My parameters are st. deviation = 50, max. search dist. = 20, transition weight = 35 on trajectory1.
![1](https://user-images.githubusercontent.com/46083088/79405798-ed9e1080-7fc7-11ea-827c-241fba671144.png)



Thanks for your help.

**Comment by visile** [comment]
The picture of corresponding steps of opening plugin from vector menu
<img width="351" alt="image" src="https://user-images.githubusercontent.com/46083088/79406097-bbd97980-7fc8-11ea-93a5-703d7e205f4e.png">
<img width="806" alt="image" src="https://user-images.githubusercontent.com/46083088/79406180-f2af8f80-7fc8-11ea-9177-1e6c0ab124db.png">


<img width="700" alt="image" src="https://user-images.githubusercontent.com/46083088/79406039-90ef2580-7fc8-11ea-813a-034439b0a8df.png">

**Comment by jagodki** [comment]
Hi,

respective your question about using the plugin via python: yes, this is possible. You can invoke the algorithm using the processing framework (you can find a description about it in the readme: [click here](https://github.com/jagodki/Offline-MapMatching#match-trajectory)). At the moment the parameters has to be adjusted manually for each trajectory. I am working on this problem for a new major release, but this will need some time to develop it, sorry :(

Respective the problem with the not visible result layer: you are using the CRS EPSG:4326, i.e. your data has geographic coordinates. Please reproject your trajectory and network into a metric CRS (you can find a hint about it in the readme: [click here](https://github.com/jagodki/Offline-MapMatching#hints-for-usage-of-the-map-matching)). The plugin calculates euclidean lengths and distances. If you are using data with geographic coordinates, you will get strange results. Maybe this is the problem. Please let me know if a reprojection of your data solves the problem.

**Comment by visile** [comment]
Hi,
Thank you very much for your help. When I change the coordinate system, I can get the result.But there are new problems. When I use my data to match road network, I can't reduce trajectory density which result is just a point.
![image](https://user-images.githubusercontent.com/46083088/89158649-00514b00-d5a1-11ea-9d5e-8ff0a6b86cb4.png)
What is more, i can not select my network(0_clip.shp) in the mapmatching.
<img width="863" alt="image" src="https://user-images.githubusercontent.com/46083088/89159151-b0bf4f00-d5a1-11ea-9b1e-47c2fa2c6a98.png">
This is my [data,](D:\mapmatching\data\data) please help me test and tell me where the problem is, thank you.

**Comment by jagodki** [comment]
Hi,

There are two problems:

1. your Network has the geometry type Multi-Linestring. Layers with multi geometries will not be available in the comboboxes, if you start the plugin via Toolbar or Menubar. You can transform your network to single geometries or start the plugin via the processing toolbox (the gui from the processing toolbox allows the selection of multigeometries). 

2. your data has the crs 4326, i.e. geographic coordinates. But the preprocessing algorithm to reduce the trajectory density requires metric coordinates from a projected crs, because you have to insert a metric value as the smallest distance between two consecutive trajectory points. Please reproject your trajectory to a projected crs and run the algorithm again. Then it should work. 

Sincerely,
Christoph

**Comment by visile** [comment]
Hi，thank you very much. I've solved the second problem but still can not solve the first one. I use the feature to line in the ARCGIS to handle the network, but the problem still exist, can you tell me how to  transform my network to single geometries in the QGIS.
Thanks!

**Comment by jagodki** [comment]
To transform your network from multi- to single-geometries, please use the function "Multipart to singleparts". This function is located in the toolbox and in the vector menu:

Toolbox (search for "Multipart"):
<img width="271" alt="image" src="https://user-images.githubusercontent.com/23242936/89821807-79c3dd00-db4f-11ea-8713-badd2706a937.png">

Vector menu:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/23242936/89821977-c0193c00-db4f-11ea-980e-4626e6c53e63.png">

**Comment by visile** [comment]
Thank you very much！I have got the perfect result.
