### ISSUE TITLE
Expected value parameter

### ISSUE THREAD

**Issue by rvinogradov** [jagodki/Offline-MapMatching#38]
Hi I have a theoretical question about the expected value. In the description of your tool it is described as: 

> the expected distance **between the positions from the trajectory and their possible positions on the network**. It is recommended to choose the value 0, i.e. ideally, the trajectory points should be on the network, if the accuracy of the coordinates would be 100%.

My question is, why is it recommended to choose a value of 0? Isn't it true that you can always be certain that the accuracy of the GPS-measurements in relation to the road network is never 100%, due to noise in the GPS data and/or the layout of the road network?

**Comment by jagodki** [comment]
Hi,

yes, you are thinking right. The background of this parameter is the following: a probability will be calculated for each candidate using a Gaussian distribution. The expected value is the distance between the measurement and your real position. In best cases, i.e. if you have a measurement with an accuracy of 100%, the distance will be zero. Because you drove on a street represented by a road network, the measurement should be on the network. But using GPS or any other GNNS, your measurements will always have an inaccuracy, which results in a distance between the candidates and the measurements bigger than zero. In a Gaussian distribution this inaccuracy will be described via the standard deviation. For this plugin I do interpret the expected value as an expected distance between candidates and measurements without inaccuracy. Imagine you would write down the distances between your location and the measurements in a 2D-coordinate system. The average of all distances for one location should go to zero, if you have an infinite count of measurements (law of large numbers). An expected value unequal zero is necessary, if your network or trajectory have an all-over offset. In this cases a measurement with 100% accuracy would result into a distance between candidate and measurement bigger than zero.

If something is not understandable, please let know it :)
