### ISSUE TITLE
Verification of map matching accuracy

### ISSUE THREAD

**Issue by visile** [jagodki/Offline-MapMatching#41]
Hello, I have two questions to ask you. Firstly, I have a user's trajectory set which contains many tracks. Is there any way to adaptively change the st. deviation and transition weight when using Python to process many tracks? Secondly, is there any way to check the accuracy of the result of road I  have matched.

**Comment by jagodki** [comment]
Hi, please have a look on the new version of the plugin a recently uploaded. Now the parameters "standard deviation" and "transition weight" will be calculated automatically described in Newson & Krumm (2009). That should make it a lot easier for batch processing in python. Also the needed computation time is now improved.

My plugin does not have any tool to check the accuracy of the results. Spontaneously I would not know how to valuate the accuracy of the results. Do you know any approach to do it?

**Comment by visile** [comment]
Thank you for you help！I'm also looking for the ways to verify the accuracy of  mapmatching.I tried the latest plug-in. The efficiency has been improved a lot, and the selection of parameters is more convenient. However, there is a problem of matching redundant road sections. How to solve this problem?
![image](https://user-images.githubusercontent.com/46083088/90707008-2416cf80-e2c9-11ea-8818-5568ebbff55d.png)

**Comment by jagodki** [comment]
If the image shows the whole trajectory, then you could decrease the maximum search distance. Without a look on your data, I think the following trajectory point produces the problem:
<img width="802" alt="Bildschirmfoto 2020-08-26 um 20 10 11" src="https://user-images.githubusercontent.com/23242936/91340426-4e402400-e7d8-11ea-95c0-3e383375f43e.png">

The new version requires more preprocessing of the input data, because less parameters are controllable by the user. But I received a lot messages with data examples where preprocessing was also necessary, regardless the controllable parameters. Because of this, I decided to create the current version as it is. For the future I will have more focus on preprocessing functions. Maybe you could also reduce the density of your trajectory. The small clusters will not produce better results, but increase the computation time.

**Comment by jagodki** [comment]
closed because of inactivity, please reopen this issue if necessary
