### ISSUE TITLE
Wrong line direction of matched trajectories

### ISSUE THREAD

**Issue by anitagraser** [jagodki/Offline-MapMatching#6]
The line directions of the matched trajectories are in the opposite direction of the order of the input trajectory points. Point labels show input order:

![selection_325](https://user-images.githubusercontent.com/590385/46148139-b2ae7d80-c267-11e8-84ee-cd4a8bbc656a.png)

**Comment by jagodki** [comment]
I had the same problem during the development of the first release and thought, that I solved it. But I can reproduce the bug. It looks like the problem ist the direction of the edges (against the direction of the trajectory). The bug should be related to the problem of issue #5. I will look for the reason of this bug.

**Comment by jagodki** [comment]
I found a problem in my code: after running Dijkstra algorithm, I did not keep in mind, that I have to collect all vertices of the shortest route between two points from the end, i.e. the target point, to the beginning, i.e. the starting point. Because each line of the result layer will be constructed using the Dijkstra algorithm, the lines had the wrong orientation. I solved this issue and uploaded a new version of the plugin to the plugin repository. Please let me know whether the bug still exists or not.

**Comment by anitagraser** [comment]
Thank you, the direction now looks correct. 
![image](https://user-images.githubusercontent.com/590385/46367070-001e5680-c67d-11e8-9b83-d4f39b1b56fc.png)
